# Generated by Django 5.2.8 on 2025-11-16 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemitem',
            options={'verbose_name': 'Item da Ordem', 'verbose_name_plural': 'Itens da Ordem'},
        ),
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'ordering': ('-data_abertura',), 'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ('-criado_em',), 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='concluido',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='data_fechamento',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='servicos',
        ),
        migrations.AddField(
            model_name='ordemitem',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço unitário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluída em'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição do problema/serviço'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('aguardando_pecas', 'Aguardando peças'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=30, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='servico',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordemitem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='ordemitem',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.servico'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_abertura',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Aberta em'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='veiculos.veiculo'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço'),
        ),
    ]
